### ISSUE TITLE
Chinese shows abnormal.

### ISSUE THREAD

**Issue by chumohua** [Ev3nt/MM-Engine#1]
Hi, I tried to use MM Engine in WAR3 TFT 1.26.
But my WAR3 is in Chinese.Unable to display characters under mm engine.
![2022-03-29](https://user-images.githubusercontent.com/59325563/160466683-96d18e7c-9cbe-4111-b6c6-481fa05a32f2.png)
![2022-03-29 (1)](https://user-images.githubusercontent.com/59325563/160466721-f919bde0-3854-4564-998a-15fb772d229f.png)

**Comment by Ev3nt** [comment]
Hi. Can you share with me your war3patch.mpq (or where's i can get chinese language)? I think it cause MME compiled with multi-bytes strings.

**Comment by chumohua** [comment]
I am very very willing, But I don't know how I can send the file to you on Github.How should I do? Or can you give me an email address?

**Comment by Ev3nt** [comment]
Sure.

event.official@mail.ru

**Comment by chumohua** [comment]
I have sent it to you,thank you.

**Comment by Ev3nt** [comment]
Ok, i found the trouble.
![image](https://user-images.githubusercontent.com/59147071/160499060-438eb3c0-f6bb-4455-a730-6892630208fb.png)
![image](https://user-images.githubusercontent.com/59147071/160498520-e5c8a304-0e23-470a-80cc-2357306dba3b.png)
Use this mpq to repair your language [MM Engine.zip](https://github.com/Ev3nt/MM-Engine/files/8366784/MM.Engine.zip)
